/* This file was generated by lv6 version 6.101.27. */
/*  lv6 -cc cruisectr.lus -n cruiseCtr */
/* on c74 the 08/02/2025 at 09:18:09 */
#include "cruisectr_cruiseCtr.h"
//// Defining step functions
// Memory initialisation for Lustre_arrow_2_ctx
void Lustre_arrow_2_ctx_reset(Lustre_arrow_2_ctx_type* ctx){  ctx->_memory = _true;
}
// Memory allocation for Lustre_arrow_2_ctx
Lustre_arrow_2_ctx_type* Lustre_arrow_2_ctx_new_ctx(){

   Lustre_arrow_2_ctx_type* ctx = (Lustre_arrow_2_ctx_type*)calloc(1, sizeof(Lustre_arrow_2_ctx_type));
   // ctx->client_data = cdata;
   Lustre_arrow_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_arrow_2_ctx
void Lustre_arrow_2_step(_boolean i1,_boolean i2,_boolean *out,Lustre_arrow_2_ctx_type* ctx){  *out = ((ctx->_memory)? i1 : i2);
  ctx->_memory = _false;

} // End of Lustre_arrow_2_step

// Memory initialisation for Lustre_arrow_ctx
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx){  ctx->_memory = _true;
}
// Memory allocation for Lustre_arrow_ctx
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx(){

   Lustre_arrow_ctx_type* ctx = (Lustre_arrow_ctx_type*)calloc(1, sizeof(Lustre_arrow_ctx_type));
   // ctx->client_data = cdata;
   Lustre_arrow_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_arrow_ctx
void Lustre_arrow_step(_real i1,_real i2,_real *out,Lustre_arrow_ctx_type* ctx){  *out = ((ctx->_memory)? i1 : i2);
  ctx->_memory = _false;

} // End of Lustre_arrow_step

// Memory initialisation for Lustre_pre_ctx
void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx){
}
// Memory allocation for Lustre_pre_ctx
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx(){

   Lustre_pre_ctx_type* ctx = (Lustre_pre_ctx_type*)calloc(1, sizeof(Lustre_pre_ctx_type));
   // ctx->client_data = cdata;
   Lustre_pre_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_pre_ctx
void Lustre_pre_get(_boolean *out,Lustre_pre_ctx_type* ctx){
  *out = ctx->_memory;

} // End of Lustre_pre_get

void Lustre_pre_set(_boolean i1,Lustre_pre_ctx_type* ctx){
  ctx->_memory = i1;

} // End of Lustre_pre_set

// Memory initialisation for Lustre_pre_2_ctx
void Lustre_pre_2_ctx_reset(Lustre_pre_2_ctx_type* ctx){
}
// Memory allocation for Lustre_pre_2_ctx
Lustre_pre_2_ctx_type* Lustre_pre_2_ctx_new_ctx(){

   Lustre_pre_2_ctx_type* ctx = (Lustre_pre_2_ctx_type*)calloc(1, sizeof(Lustre_pre_2_ctx_type));
   // ctx->client_data = cdata;
   Lustre_pre_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_pre_2_ctx
void Lustre_pre_2_get(_real *out,Lustre_pre_2_ctx_type* ctx){
  *out = ctx->_memory;

} // End of Lustre_pre_2_get

void Lustre_pre_2_set(_real i1,Lustre_pre_2_ctx_type* ctx){
  ctx->_memory = i1;

} // End of Lustre_pre_2_set

// Step function(s) for cruisectr_abs_ctx
void cruisectr_abs_step(_real x,_real *y){
   _real _split_2;
   _boolean _split_1;

  _split_2 = - x;
  _split_1 = x >= 0.0;
   if (_split_1 == _true) {
     *y = x;
   } else {
     *y = _split_2;
   }

} // End of cruisectr_abs_step

// Step function(s) for cruisectr_changeSpeed_ctx
void cruisectr_changeSpeed_step(_real rotate,_real f,_boolean on,_real *new_rotate){
   _real _split_4;
   _boolean _split_3;

  _split_4 = rotate + f;
  _split_3 = ! on;
   if (_split_3 == _true) {
     *new_rotate = rotate;
   } else {
     *new_rotate = _split_4;
   }

} // End of cruisectr_changeSpeed_step

// Memory initialisation for cruisectr_controlSpeed_ctx
void cruisectr_controlSpeed_ctx_reset(cruisectr_controlSpeed_ctx_type* ctx){
  int _i;

    Lustre_pre_2_ctx_reset(&ctx->Lustre_pre_2_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
}
// Memory allocation for cruisectr_controlSpeed_ctx
cruisectr_controlSpeed_ctx_type* cruisectr_controlSpeed_ctx_new_ctx(){

   cruisectr_controlSpeed_ctx_type* ctx = (cruisectr_controlSpeed_ctx_type*)calloc(1, sizeof(cruisectr_controlSpeed_ctx_type));
   // ctx->client_data = cdata;
   cruisectr_controlSpeed_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for cruisectr_controlSpeed_ctx
void cruisectr_controlSpeed_step(_real cruiseSpeed,_real speed,_real *f,cruisectr_controlSpeed_ctx_type* ctx){   _real _split_24;
   _real _split_23;
   _real _split_22;
   _real _split_21;
   _real _split_20;
   _boolean _split_19;
   _boolean _split_18;
   _real _split_17;
   _real _split_16;
   _real _split_15;
   _real _split_14;
   _real _split_13;
   _boolean _split_12;
   _boolean _split_11;
   _boolean _split_10;
   _real _split_9;
   _real _split_8;
   _boolean _split_7;
   _real _split_6;
   _real _split_5;
   _real error;
   _real prev_f;

  Lustre_pre_2_get(&_split_5,&ctx->Lustre_pre_2_ctx_tab[0]); 
  Lustre_arrow_step(0.0,_split_5,&prev_f,&ctx->Lustre_arrow_ctx_tab[0]); 
  cruisectr_abs_step(prev_f,&_split_17); 
  _split_18 = _split_17 < 0.1;
  _split_19 = prev_f > 0.0;
  _split_20 = - 1.0;
   if (_split_19 == _true) {
     _split_21 = 1.0;
   } else {
     _split_21 = _split_20;
   }
  _split_22 = 0.15 * _split_21;
  _split_23 = prev_f - _split_22;
   if (_split_18 == _true) {
     _split_24 = 0.0;
   } else {
     _split_24 = _split_23;
   }
  error = cruiseSpeed - speed;
  cruisectr_abs_step(error,&_split_6); 
  _split_7 = _split_6 > 0.5;
  cruisectr_abs_step(error,&_split_8); 
  cruisectr_abs_step(prev_f,&_split_9); 
  _split_10 = _split_8 < _split_9;
  _split_11 = _split_7 & _split_10;
  _split_12 = error > 0.0;
  _split_13 = - 1.0;
   if (_split_12 == _true) {
     _split_14 = 1.0;
   } else {
     _split_14 = _split_13;
   }
  _split_15 = 0.25 * _split_14;
  _split_16 = prev_f + _split_15;
   if (_split_11 == _true) {
     *f = _split_16;
   } else {
     *f = _split_24;
   }
  Lustre_pre_2_set(*f,&ctx->Lustre_pre_2_ctx_tab[0]); 

} // End of cruisectr_controlSpeed_step

// Memory initialisation for cruisectr_cruiseCtr_ctx
void cruisectr_cruiseCtr_ctx_reset(cruisectr_cruiseCtr_ctx_type* ctx){
  int _i;

    cruisectr_setSpeed_ctx_reset(&ctx->cruisectr_setSpeed_ctx_tab[0]);
    cruisectr_controlSpeed_ctx_reset(&ctx->cruisectr_controlSpeed_ctx_tab[0]);
    Lustre_pre_2_ctx_reset(&ctx->Lustre_pre_2_ctx_tab[0]);
    Lustre_pre_2_ctx_reset(&ctx->Lustre_pre_2_ctx_tab[1]);
    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[1]);
    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[2]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Lustre_arrow_2_ctx_reset(&ctx->Lustre_arrow_2_ctx_tab[0]);
}
// Memory allocation for cruisectr_cruiseCtr_ctx
cruisectr_cruiseCtr_ctx_type* cruisectr_cruiseCtr_ctx_new_ctx(){

   cruisectr_cruiseCtr_ctx_type* ctx = (cruisectr_cruiseCtr_ctx_type*)calloc(1, sizeof(cruisectr_cruiseCtr_ctx_type));
   // ctx->client_data = cdata;
   cruisectr_cruiseCtr_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for cruisectr_cruiseCtr_ctx
void cruisectr_cruiseCtr_step(_boolean cruise,_boolean inc,_boolean dec,_real rotate_in,_boolean *on,_real *speed,_real *cruiseSpeed_out,_real *f_out,cruisectr_cruiseCtr_ctx_type* ctx){   _boolean _split_32;
   _boolean _split_31;
   _real _split_30;
   _real _split_29;
   _boolean _split_28;
   _real _split_27;
   _real _split_26;
   _boolean _split_25;
   _real speed_val;
   _boolean on_state;
   _real cruise_spd;
   _real force;
   _real current_rotate;

  Lustre_pre_get(&_split_25,&ctx->Lustre_pre_ctx_tab[1]); 
  Lustre_pre_2_get(&_split_26,&ctx->Lustre_pre_2_ctx_tab[1]); 
  Lustre_pre_2_get(&_split_27,&ctx->Lustre_pre_2_ctx_tab[0]); 
  Lustre_pre_get(&_split_28,&ctx->Lustre_pre_ctx_tab[0]); 
  cruisectr_changeSpeed_step(_split_26,_split_27,_split_28,&_split_29); 
   if (_split_25 == _true) {
     _split_30 = _split_29;
   } else {
     _split_30 = rotate_in;
   }
  Lustre_arrow_step(0.0,_split_30,&current_rotate,&ctx->Lustre_arrow_ctx_tab[0]); 
  cruisectr_measureSpeed_step(current_rotate,&speed_val); 
  Lustre_pre_get(&_split_31,&ctx->Lustre_pre_ctx_tab[2]); 
  Lustre_arrow_2_step(_false,_split_31,&_split_32,&ctx->Lustre_arrow_2_ctx_tab[0]); 
  cruisectr_setSpeed_step(cruise,inc,dec,speed_val,_split_32,&on_state,&cruise_spd,&ctx->cruisectr_setSpeed_ctx_tab[0]); 
  Lustre_pre_set(on_state,&ctx->Lustre_pre_ctx_tab[0]); 
  cruisectr_controlSpeed_step(cruise_spd,speed_val,&force,&ctx->cruisectr_controlSpeed_ctx_tab[0]); 
  Lustre_pre_2_set(force,&ctx->Lustre_pre_2_ctx_tab[0]); 
  Lustre_pre_2_set(current_rotate,&ctx->Lustre_pre_2_ctx_tab[1]); 
  Lustre_pre_set(on_state,&ctx->Lustre_pre_ctx_tab[1]); 
  Lustre_pre_set(on_state,&ctx->Lustre_pre_ctx_tab[2]); 
  *on = on_state;
  *speed = speed_val;
  *cruiseSpeed_out = cruise_spd;
   if (on_state == _true) {
     *f_out = force;
   } else {
     *f_out = 0.0;
   }

} // End of cruisectr_cruiseCtr_step

// Step function(s) for cruisectr_measureSpeed_ctx
void cruisectr_measureSpeed_step(_real rotate,_real *speed){
   _real _split_34;
   _real _split_33;

  _split_33 = rotate * 10.0;
  _split_34 = _split_33 * 60.0;
  *speed = _split_34 / 672.0;

} // End of cruisectr_measureSpeed_step

// Memory initialisation for cruisectr_setSpeed_ctx
void cruisectr_setSpeed_ctx_reset(cruisectr_setSpeed_ctx_type* ctx){
  int _i;

    Lustre_pre_2_ctx_reset(&ctx->Lustre_pre_2_ctx_tab[0]);  for (_i=0 ; _i<4 ; _i+=1){
    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[_i]);
 }
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Lustre_arrow_2_ctx_reset(&ctx->Lustre_arrow_2_ctx_tab[0]);
}
// Memory allocation for cruisectr_setSpeed_ctx
cruisectr_setSpeed_ctx_type* cruisectr_setSpeed_ctx_new_ctx(){

   cruisectr_setSpeed_ctx_type* ctx = (cruisectr_setSpeed_ctx_type*)calloc(1, sizeof(cruisectr_setSpeed_ctx_type));
   // ctx->client_data = cdata;
   cruisectr_setSpeed_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for cruisectr_setSpeed_ctx
void cruisectr_setSpeed_step(_boolean cruise,_boolean inc,_boolean dec,_real speed,_boolean pon,_boolean *on,_real *cruiseSpeed,cruisectr_setSpeed_ctx_type* ctx){   _real _split_49;
   _real _split_48;
   _real _split_47;
   _real _split_46;
   _real _split_45;
   _boolean _split_44;
   _boolean _split_43;
   _boolean _split_42;
   _boolean _split_41;
   _boolean _split_40;
   _boolean _split_39;
   _boolean _split_38;
   _real _split_37;
   _real _split_36;
   _boolean _split_35;
   _real prevSpeed;

  Lustre_pre_get(&_split_35,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_pre_2_get(&_split_36,&ctx->Lustre_pre_2_ctx_tab[0]); 
   if (_split_35 == _true) {
     _split_37 = _split_36;
   } else {
     _split_37 = speed;
   }
  Lustre_pre_get(&_split_42,&ctx->Lustre_pre_ctx_tab[3]); 
  _split_43 = ! _split_42;
  Lustre_pre_get(&_split_40,&ctx->Lustre_pre_ctx_tab[1]); 
  Lustre_pre_get(&_split_38,&ctx->Lustre_pre_ctx_tab[2]); 
  _split_39 = ! _split_38;
   if (cruise == _true) {
     _split_41 = _split_39;
   } else {
     _split_41 = _split_40;
   }
  Lustre_arrow_2_step(_false,_split_41,on,&ctx->Lustre_arrow_2_ctx_tab[0]); 
  _split_44 = *on & _split_43;
   if (dec == _true) {
     _split_47 = 1.0;
   } else {
     _split_47 = 0.0;
   }
   if (inc == _true) {
     _split_45 = 1.0;
   } else {
     _split_45 = 0.0;
   }
  Lustre_arrow_step(0.0,_split_37,&prevSpeed,&ctx->Lustre_arrow_ctx_tab[0]); 
  _split_46 = prevSpeed + _split_45;
  _split_48 = _split_46 - _split_47;
   if (*on == _true) {
     _split_49 = _split_48;
   } else {
     _split_49 = prevSpeed;
   }
   if (_split_44 == _true) {
     *cruiseSpeed = speed;
   } else {
     *cruiseSpeed = _split_49;
   }
  Lustre_pre_2_set(*cruiseSpeed,&ctx->Lustre_pre_2_ctx_tab[0]); 
  Lustre_pre_set(*on,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_pre_set(*on,&ctx->Lustre_pre_ctx_tab[1]); 
  Lustre_pre_set(*on,&ctx->Lustre_pre_ctx_tab[2]); 
  Lustre_pre_set(*on,&ctx->Lustre_pre_ctx_tab[3]); 

} // End of cruisectr_setSpeed_step

