/* This file was generated by lv6 version 6.101.27. */
/*  lv6 -cc cruiseCtr.lus -n cruiseCtr */
/* on c74 the 08/02/2025 at 09:32:32 */

#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include "cruiseCtr_cruiseCtr.h" 
/* Print a promt ? ************************/
static int ISATTY;
/* MACROS DEFINITIONS ****************/
#ifndef TT
#define TT "1"
#endif
#ifndef FF
#define FF "0"
#endif
#ifndef BB
#define BB "bottom"
#endif
#ifdef CKCHECK
/* set this macro for testing output clocks */
#endif

void _read_pragma(cruiseCtr_cruiseCtr_ctx_type* ctx,char b[]) {
   int s = 1;

   if (!strcmp(b,"#quit")) exit(0);
   if (!strcmp(b,"#q")) exit(0);
   if (!strcmp(b,"#reset")) cruiseCtr_cruiseCtr_ctx_reset(ctx);
   return;
}

/* Standard Input procedures **************/
_boolean _get_bool(cruiseCtr_cruiseCtr_ctx_type* ctx,char* n){
   char b[512];
   char c;
   _boolean r = 0;
   int s = 1;
   do {
      if(ISATTY) {
         if((s != 1)||(r == -1)) printf("\a");
         // printf("%s (1,t,T/0,f,F) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      r = -1;
      c=b[0];
      if(c == 'q') exit(0);
      if(c == '#') _read_pragma(ctx,b);
      if((c == '0') || (c == 'f') || (c == 'F')) r = 0;
      if((c == '1') || (c == 't') || (c == 'T')) r = 1;
   } while((s != 1) || (r == -1));
   return r;
}
_integer _get_int(cruiseCtr_cruiseCtr_ctx_type* ctx,char* n){
   char b[512];
   _integer r;
   int s = 1;
   do {
      if(ISATTY) {
         if(s != 1) printf("\a");
         //printf("%s (integer) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      if(*b == 'q') exit(0);
      if(*b == '#') {
         _read_pragma(ctx,b);
      } else {
        s = sscanf(b, "%d", &r);
      }
   } while(s != 1);
   return r;
}
#define REALFORMAT ((sizeof(_real)==8)?"%lf":"%f")
_real _get_real(cruiseCtr_cruiseCtr_ctx_type* ctx,char* n){
   char b[512];
   _real r;
   int s = 1;
   do {
      if(ISATTY) {
         if(s != 1) printf("\a");
         //printf("%s (real) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      if(*b == 'q') exit(0);
      if(*b == '#') {
         _read_pragma(ctx,b);
      } else {
         s = sscanf(b, REALFORMAT, &r);
      }
   } while(s != 1);
   return r;
}
char* _get_string(cruiseCtr_cruiseCtr_ctx_type* ctx,char* n){
   char b[512];
   char* r;
   int s = 1;
   do {
      if(ISATTY) {
         if(s != 1) printf("\a");
         //printf("%s (real) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      if(*b == '#') {
         _read_pragma(ctx,b);
      }
   } while(s != 1);
   r =  b;
   return r;
}
/* Standard Output procedures **************/
void _put_bottom(char* n){
   if(ISATTY) printf("%s = ", n);
   printf("%s ", BB);
   if(ISATTY) printf("\n");
}
void _put_bool(char* n, _boolean _V){
   if(ISATTY) printf("%s = ", n);
   printf("%s ", (_V)? TT : FF);
   if(ISATTY) printf("\n");
}
void _put_int(char* n, _integer _V){
   if(ISATTY) printf("%s = ", n);
   printf("%d ", _V);
   if(ISATTY) printf("\n");
}
void _put_real(char* n, _real _V){
   if(ISATTY) printf("%s = ", n);
   printf("%f ", _V);
   if(ISATTY) printf("\n");
}
void _put_string(char* n, char* _V){
   if(ISATTY) printf("%s = ", n);
   printf("%s ", _V);
   if(ISATTY) printf("\n");
}

/* Output procedures **********************/
#ifdef CKCHECK
void %s_BOT_n(void* cdata){
   _put_bottom("n");
}
#endif

/* Main procedure *************************/
int main(){
  int _s = 0;
  _boolean cruise;
  _boolean inc;
  _boolean dec;
  _real sensor_rotate;
  _boolean on;
  _real speed;
  _real cruiseSpeed;
  _real f;
    cruiseCtr_cruiseCtr_ctx_type* ctx = cruiseCtr_cruiseCtr_ctx_new_ctx(NULL);

  printf("#inputs \"cruise\":bool \"inc\":bool \"dec\":bool \"sensor_rotate\":real\n");
  printf("#outputs \"on\":bool \"speed\":real \"cruiseSpeed\":real \"f\":real\n");

  /* Main loop */
  ISATTY = isatty(0);
  while(1){
    if (ISATTY) printf("#step %d \n", _s+1);
    else if(_s) printf("\n");
    fflush(stdout);
    ++_s;
    cruise = _get_bool(ctx,"cruise");
    inc = _get_bool(ctx,"inc");
    dec = _get_bool(ctx,"dec");
    sensor_rotate = _get_real(ctx,"sensor_rotate");
    cruiseCtr_cruiseCtr_step(cruise,inc,dec,sensor_rotate,&on,&speed,&cruiseSpeed,&f,ctx);
    // printf("%d %d %d %f #outs %d %f %f %f\n",cruise,inc,dec,sensor_rotate,on,speed,cruiseSpeed,f);
    printf("%d %f %f %f\n",on,speed,cruiseSpeed,f);
  }
  return 1;
   
}
