/* This file was generated by lv6 version 6.101.27. */
/*  lv6 -cc cruiseCtr.lus -n cruiseCtr */
/* on c74 the 08/02/2025 at 09:32:32 */
#include "cruiseCtr_cruiseCtr.h"
//// Defining step functions
// Memory initialisation for Lustre_arrow_2_ctx
void Lustre_arrow_2_ctx_reset(Lustre_arrow_2_ctx_type* ctx){  ctx->_memory = _true;
}
// Memory allocation for Lustre_arrow_2_ctx
Lustre_arrow_2_ctx_type* Lustre_arrow_2_ctx_new_ctx(){

   Lustre_arrow_2_ctx_type* ctx = (Lustre_arrow_2_ctx_type*)calloc(1, sizeof(Lustre_arrow_2_ctx_type));
   // ctx->client_data = cdata;
   Lustre_arrow_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_arrow_2_ctx
void Lustre_arrow_2_step(_boolean i1,_boolean i2,_boolean *out,Lustre_arrow_2_ctx_type* ctx){  *out = ((ctx->_memory)? i1 : i2);
  ctx->_memory = _false;

} // End of Lustre_arrow_2_step

// Memory initialisation for Lustre_arrow_ctx
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx){  ctx->_memory = _true;
}
// Memory allocation for Lustre_arrow_ctx
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx(){

   Lustre_arrow_ctx_type* ctx = (Lustre_arrow_ctx_type*)calloc(1, sizeof(Lustre_arrow_ctx_type));
   // ctx->client_data = cdata;
   Lustre_arrow_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_arrow_ctx
void Lustre_arrow_step(_real i1,_real i2,_real *out,Lustre_arrow_ctx_type* ctx){  *out = ((ctx->_memory)? i1 : i2);
  ctx->_memory = _false;

} // End of Lustre_arrow_step

// Memory initialisation for Lustre_pre_2_ctx
void Lustre_pre_2_ctx_reset(Lustre_pre_2_ctx_type* ctx){
}
// Memory allocation for Lustre_pre_2_ctx
Lustre_pre_2_ctx_type* Lustre_pre_2_ctx_new_ctx(){

   Lustre_pre_2_ctx_type* ctx = (Lustre_pre_2_ctx_type*)calloc(1, sizeof(Lustre_pre_2_ctx_type));
   // ctx->client_data = cdata;
   Lustre_pre_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_pre_2_ctx
void Lustre_pre_2_get(_boolean *out,Lustre_pre_2_ctx_type* ctx){
  *out = ctx->_memory;

} // End of Lustre_pre_2_get

void Lustre_pre_2_set(_boolean i1,Lustre_pre_2_ctx_type* ctx){
  ctx->_memory = i1;

} // End of Lustre_pre_2_set

// Memory initialisation for Lustre_pre_ctx
void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx){
}
// Memory allocation for Lustre_pre_ctx
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx(){

   Lustre_pre_ctx_type* ctx = (Lustre_pre_ctx_type*)calloc(1, sizeof(Lustre_pre_ctx_type));
   // ctx->client_data = cdata;
   Lustre_pre_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_pre_ctx
void Lustre_pre_get(_real *out,Lustre_pre_ctx_type* ctx){
  *out = ctx->_memory;

} // End of Lustre_pre_get

void Lustre_pre_set(_real i1,Lustre_pre_ctx_type* ctx){
  ctx->_memory = i1;

} // End of Lustre_pre_set

// Step function(s) for cruiseCtr_abs_ctx
void cruiseCtr_abs_step(_real x,_real *y){
   _real _split_2;
   _boolean _split_1;

  _split_2 = - x;
  _split_1 = x >= 0.0;
   if (_split_1 == _true) {
     *y = x;
   } else {
     *y = _split_2;
   }

} // End of cruiseCtr_abs_step

// Memory initialisation for cruiseCtr_controlSpeed_ctx
void cruiseCtr_controlSpeed_ctx_reset(cruiseCtr_controlSpeed_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
}
// Memory allocation for cruiseCtr_controlSpeed_ctx
cruiseCtr_controlSpeed_ctx_type* cruiseCtr_controlSpeed_ctx_new_ctx(){

   cruiseCtr_controlSpeed_ctx_type* ctx = (cruiseCtr_controlSpeed_ctx_type*)calloc(1, sizeof(cruiseCtr_controlSpeed_ctx_type));
   // ctx->client_data = cdata;
   cruiseCtr_controlSpeed_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for cruiseCtr_controlSpeed_ctx
void cruiseCtr_controlSpeed_step(_real cruiseSpeed,_real speed,_real *f,cruiseCtr_controlSpeed_ctx_type* ctx){   _real _split_22;
   _real _split_21;
   _real _split_20;
   _real _split_19;
   _real _split_18;
   _boolean _split_17;
   _boolean _split_16;
   _real _split_15;
   _real _split_14;
   _real _split_13;
   _real _split_12;
   _real _split_11;
   _boolean _split_10;
   _boolean _split_9;
   _boolean _split_8;
   _real _split_7;
   _real _split_6;
   _boolean _split_5;
   _real _split_4;
   _real _split_3;
   _real error;
   _real prev_f;

  Lustre_pre_get(&_split_3,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(0.0,_split_3,&prev_f,&ctx->Lustre_arrow_ctx_tab[0]); 
  cruiseCtr_abs_step(prev_f,&_split_15); 
  _split_16 = _split_15 < 0.1;
  _split_17 = prev_f > 0.0;
  _split_18 = - 1.0;
   if (_split_17 == _true) {
     _split_19 = 1.0;
   } else {
     _split_19 = _split_18;
   }
  _split_20 = 0.15 * _split_19;
  _split_21 = prev_f - _split_20;
   if (_split_16 == _true) {
     _split_22 = 0.0;
   } else {
     _split_22 = _split_21;
   }
  error = cruiseSpeed - speed;
  cruiseCtr_abs_step(error,&_split_4); 
  _split_5 = _split_4 > 0.5;
  cruiseCtr_abs_step(error,&_split_6); 
  cruiseCtr_abs_step(prev_f,&_split_7); 
  _split_8 = _split_6 < _split_7;
  _split_9 = _split_5 & _split_8;
  _split_10 = error > 0.0;
  _split_11 = - 1.0;
   if (_split_10 == _true) {
     _split_12 = 1.0;
   } else {
     _split_12 = _split_11;
   }
  _split_13 = 0.25 * _split_12;
  _split_14 = prev_f + _split_13;
   if (_split_9 == _true) {
     *f = _split_14;
   } else {
     *f = _split_22;
   }
  Lustre_pre_set(*f,&ctx->Lustre_pre_ctx_tab[0]); 

} // End of cruiseCtr_controlSpeed_step

// Memory initialisation for cruiseCtr_cruiseCtr_ctx
void cruiseCtr_cruiseCtr_ctx_reset(cruiseCtr_cruiseCtr_ctx_type* ctx){
  int _i;

    cruiseCtr_setSpeed_ctx_reset(&ctx->cruiseCtr_setSpeed_ctx_tab[0]);
    cruiseCtr_controlSpeed_ctx_reset(&ctx->cruiseCtr_controlSpeed_ctx_tab[0]);
    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_pre_2_ctx_reset(&ctx->Lustre_pre_2_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Lustre_arrow_2_ctx_reset(&ctx->Lustre_arrow_2_ctx_tab[0]);
}
// Memory allocation for cruiseCtr_cruiseCtr_ctx
cruiseCtr_cruiseCtr_ctx_type* cruiseCtr_cruiseCtr_ctx_new_ctx(){

   cruiseCtr_cruiseCtr_ctx_type* ctx = (cruiseCtr_cruiseCtr_ctx_type*)calloc(1, sizeof(cruiseCtr_cruiseCtr_ctx_type));
   // ctx->client_data = cdata;
   cruiseCtr_cruiseCtr_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for cruiseCtr_cruiseCtr_ctx
void cruiseCtr_cruiseCtr_step(_boolean cruise,_boolean inc,_boolean dec,_real sensor_rotate,_boolean *on,_real *speed,_real *cruiseSpeed,_real *f,cruiseCtr_cruiseCtr_ctx_type* ctx){   _real _split_28;
   _boolean _split_27;
   _real _split_26;
   _boolean _split_25;
   _boolean _split_24;
   _real _split_23;
   _real internal_rotate;
   _real current_speed;
   _boolean cruise_state;
   _real target_speed;
   _real control_force;
   _real prev_rotate;

  Lustre_pre_get(&_split_23,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(0.0,_split_23,&prev_rotate,&ctx->Lustre_arrow_ctx_tab[0]); 
  cruiseCtr_measureSpeed_step(prev_rotate,&current_speed); 
  Lustre_pre_2_get(&_split_24,&ctx->Lustre_pre_2_ctx_tab[0]); 
  Lustre_arrow_2_step(_false,_split_24,&_split_25,&ctx->Lustre_arrow_2_ctx_tab[0]); 
  cruiseCtr_setSpeed_step(cruise,inc,dec,current_speed,_split_25,&cruise_state,&target_speed,&ctx->cruiseCtr_setSpeed_ctx_tab[0]); 
  _split_27 = ! cruise_state;
  cruiseCtr_controlSpeed_step(target_speed,current_speed,&_split_26,&ctx->cruiseCtr_controlSpeed_ctx_tab[0]); 
   if (cruise_state == _true) {
     control_force = _split_26;
   } else {
     control_force = 0.0;
   }
  _split_28 = prev_rotate + control_force;
   if (_split_27 == _true) {
     internal_rotate = sensor_rotate;
   } else {
     internal_rotate = _split_28;
   }
  Lustre_pre_set(internal_rotate,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_pre_2_set(cruise_state,&ctx->Lustre_pre_2_ctx_tab[0]); 
  *on = cruise_state;
  *speed = current_speed;
  *cruiseSpeed = target_speed;
  *f = control_force;

} // End of cruiseCtr_cruiseCtr_step

// Step function(s) for cruiseCtr_measureSpeed_ctx
void cruiseCtr_measureSpeed_step(_real rotate,_real *speed){
   _real _split_30;
   _real _split_29;

  _split_29 = rotate * 10.0;
  _split_30 = _split_29 * 60.0;
  *speed = _split_30 / 672.0;

} // End of cruiseCtr_measureSpeed_step

// Memory initialisation for cruiseCtr_setSpeed_ctx
void cruiseCtr_setSpeed_ctx_reset(cruiseCtr_setSpeed_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);  for (_i=0 ; _i<4 ; _i+=1){
    Lustre_pre_2_ctx_reset(&ctx->Lustre_pre_2_ctx_tab[_i]);
 }
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Lustre_arrow_2_ctx_reset(&ctx->Lustre_arrow_2_ctx_tab[0]);
}
// Memory allocation for cruiseCtr_setSpeed_ctx
cruiseCtr_setSpeed_ctx_type* cruiseCtr_setSpeed_ctx_new_ctx(){

   cruiseCtr_setSpeed_ctx_type* ctx = (cruiseCtr_setSpeed_ctx_type*)calloc(1, sizeof(cruiseCtr_setSpeed_ctx_type));
   // ctx->client_data = cdata;
   cruiseCtr_setSpeed_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for cruiseCtr_setSpeed_ctx
void cruiseCtr_setSpeed_step(_boolean cruise,_boolean inc,_boolean dec,_real speed,_boolean pon,_boolean *on,_real *cruiseSpeed,cruiseCtr_setSpeed_ctx_type* ctx){   _real _split_45;
   _real _split_44;
   _real _split_43;
   _real _split_42;
   _real _split_41;
   _boolean _split_40;
   _boolean _split_39;
   _boolean _split_38;
   _boolean _split_37;
   _boolean _split_36;
   _boolean _split_35;
   _boolean _split_34;
   _real _split_33;
   _real _split_32;
   _boolean _split_31;
   _real prevSpeed;

  Lustre_pre_2_get(&_split_31,&ctx->Lustre_pre_2_ctx_tab[0]); 
  Lustre_pre_get(&_split_32,&ctx->Lustre_pre_ctx_tab[0]); 
   if (_split_31 == _true) {
     _split_33 = _split_32;
   } else {
     _split_33 = speed;
   }
  Lustre_pre_2_get(&_split_38,&ctx->Lustre_pre_2_ctx_tab[3]); 
  _split_39 = ! _split_38;
  Lustre_pre_2_get(&_split_36,&ctx->Lustre_pre_2_ctx_tab[1]); 
  Lustre_pre_2_get(&_split_34,&ctx->Lustre_pre_2_ctx_tab[2]); 
  _split_35 = ! _split_34;
   if (cruise == _true) {
     _split_37 = _split_35;
   } else {
     _split_37 = _split_36;
   }
  Lustre_arrow_2_step(_false,_split_37,on,&ctx->Lustre_arrow_2_ctx_tab[0]); 
  _split_40 = *on & _split_39;
   if (dec == _true) {
     _split_43 = 1.0;
   } else {
     _split_43 = 0.0;
   }
   if (inc == _true) {
     _split_41 = 1.0;
   } else {
     _split_41 = 0.0;
   }
  Lustre_arrow_step(0.0,_split_33,&prevSpeed,&ctx->Lustre_arrow_ctx_tab[0]); 
  _split_42 = prevSpeed + _split_41;
  _split_44 = _split_42 - _split_43;
   if (*on == _true) {
     _split_45 = _split_44;
   } else {
     _split_45 = prevSpeed;
   }
   if (_split_40 == _true) {
     *cruiseSpeed = speed;
   } else {
     *cruiseSpeed = _split_45;
   }
  Lustre_pre_set(*cruiseSpeed,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_pre_2_set(*on,&ctx->Lustre_pre_2_ctx_tab[0]); 
  Lustre_pre_2_set(*on,&ctx->Lustre_pre_2_ctx_tab[1]); 
  Lustre_pre_2_set(*on,&ctx->Lustre_pre_2_ctx_tab[2]); 
  Lustre_pre_2_set(*on,&ctx->Lustre_pre_2_ctx_tab[3]); 

} // End of cruiseCtr_setSpeed_step

