/* This file was generated by lv6 version 6.101.27. */
/*  lv6 -cc cruisectr.lus -n cruiseCtr */
/* on c74 the 08/02/2025 at 09:18:09 */

#include <stdlib.h>
#include <string.h>

#include "lustre_consts.h"

#ifndef _cruisectr_cruiseCtr_H_FILE
#define _cruisectr_cruiseCtr_H_FILE
void Lustre_arrow_2_ctx_reset(Lustre_arrow_2_ctx_type* ctx);
Lustre_arrow_2_ctx_type* Lustre_arrow_2_ctx_new_ctx();
void Lustre_arrow_2_step(_boolean ,_boolean ,_boolean *,Lustre_arrow_2_ctx_type*);

void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx();
void Lustre_arrow_step(_real ,_real ,_real *,Lustre_arrow_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx();
void Lustre_pre_get(_boolean *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_boolean ,Lustre_pre_ctx_type*);

void Lustre_pre_2_ctx_reset(Lustre_pre_2_ctx_type* ctx);
Lustre_pre_2_ctx_type* Lustre_pre_2_ctx_new_ctx();
void Lustre_pre_2_get(_real *,Lustre_pre_2_ctx_type*);

void Lustre_pre_2_set(_real ,Lustre_pre_2_ctx_type*);

void cruisectr_abs_step(_real ,_real *);

void cruisectr_changeSpeed_step(_real ,_real ,_boolean ,_real *);

void cruisectr_controlSpeed_ctx_reset(cruisectr_controlSpeed_ctx_type* ctx);
cruisectr_controlSpeed_ctx_type* cruisectr_controlSpeed_ctx_new_ctx();
void cruisectr_controlSpeed_step(_real ,_real ,_real *,cruisectr_controlSpeed_ctx_type*);

void cruisectr_cruiseCtr_ctx_reset(cruisectr_cruiseCtr_ctx_type* ctx);
cruisectr_cruiseCtr_ctx_type* cruisectr_cruiseCtr_ctx_new_ctx();
void cruisectr_cruiseCtr_step(_boolean ,_boolean ,_boolean ,_real ,_boolean *,_real *,_real *,_real *,cruisectr_cruiseCtr_ctx_type*);

void cruisectr_measureSpeed_step(_real ,_real *);

void cruisectr_setSpeed_ctx_reset(cruisectr_setSpeed_ctx_type* ctx);
cruisectr_setSpeed_ctx_type* cruisectr_setSpeed_ctx_new_ctx();
void cruisectr_setSpeed_step(_boolean ,_boolean ,_boolean ,_real ,_boolean ,_boolean *,_real *,cruisectr_setSpeed_ctx_type*);

/////////////////////////////////////////////////
#endif
