/* This file was generated by lv6 version 6.101.27. */
/*  lv6 -cc cruiseCtr.lus -n cruiseCtr */
/* on c74 the 08/02/2025 at 09:32:32 */

#include <stdlib.h>
#include <string.h>

#include "lustre_consts.h"

#ifndef _cruiseCtr_cruiseCtr_H_FILE
#define _cruiseCtr_cruiseCtr_H_FILE
void Lustre_arrow_2_ctx_reset(Lustre_arrow_2_ctx_type* ctx);
Lustre_arrow_2_ctx_type* Lustre_arrow_2_ctx_new_ctx();
void Lustre_arrow_2_step(_boolean ,_boolean ,_boolean *,Lustre_arrow_2_ctx_type*);

void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx();
void Lustre_arrow_step(_real ,_real ,_real *,Lustre_arrow_ctx_type*);

void Lustre_pre_2_ctx_reset(Lustre_pre_2_ctx_type* ctx);
Lustre_pre_2_ctx_type* Lustre_pre_2_ctx_new_ctx();
void Lustre_pre_2_get(_boolean *,Lustre_pre_2_ctx_type*);

void Lustre_pre_2_set(_boolean ,Lustre_pre_2_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx();
void Lustre_pre_get(_real *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_real ,Lustre_pre_ctx_type*);

void cruiseCtr_abs_step(_real ,_real *);

void cruiseCtr_controlSpeed_ctx_reset(cruiseCtr_controlSpeed_ctx_type* ctx);
cruiseCtr_controlSpeed_ctx_type* cruiseCtr_controlSpeed_ctx_new_ctx();
void cruiseCtr_controlSpeed_step(_real ,_real ,_real *,cruiseCtr_controlSpeed_ctx_type*);

void cruiseCtr_cruiseCtr_ctx_reset(cruiseCtr_cruiseCtr_ctx_type* ctx);
cruiseCtr_cruiseCtr_ctx_type* cruiseCtr_cruiseCtr_ctx_new_ctx();
void cruiseCtr_cruiseCtr_step(_boolean ,_boolean ,_boolean ,_real ,_boolean *,_real *,_real *,_real *,cruiseCtr_cruiseCtr_ctx_type*);

void cruiseCtr_measureSpeed_step(_real ,_real *);

void cruiseCtr_setSpeed_ctx_reset(cruiseCtr_setSpeed_ctx_type* ctx);
cruiseCtr_setSpeed_ctx_type* cruiseCtr_setSpeed_ctx_new_ctx();
void cruiseCtr_setSpeed_step(_boolean ,_boolean ,_boolean ,_real ,_boolean ,_boolean *,_real *,cruiseCtr_setSpeed_ctx_type*);

/////////////////////////////////////////////////
#endif
