/* This file was generated by lv6 version 6.101.27. */
/*  lv6 -cc cruiseCtr.lus -n cruiseCtr */
/* on c74 the 08/02/2025 at 09:32:32 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES
// User typedef 
#ifndef _cruiseCtr_cruiseCtr_TYPES
#define _cruiseCtr_cruiseCtr_TYPES
#endif // enf of  _cruiseCtr_cruiseCtr_TYPES
// Memoryless soc ctx typedef 
// Memoryfull soc ctx typedef 
/* Lustre_pre_ctx */
typedef struct {
   /*Memory cell*/
   _real _memory ;
} Lustre_pre_ctx_type;

/* Lustre_arrow_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_arrow_ctx_type;

/* Lustre_arrow_2_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_arrow_2_ctx_type;

/* Lustre_pre_2_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_pre_2_ctx_type;

/* cruiseCtr_setSpeed_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_pre_2_ctx_type Lustre_pre_2_ctx_tab[4];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Lustre_arrow_2_ctx_type Lustre_arrow_2_ctx_tab[1];
} cruiseCtr_setSpeed_ctx_type;

/* cruiseCtr_controlSpeed_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
} cruiseCtr_controlSpeed_ctx_type;

/* cruiseCtr_cruiseCtr_ctx */
typedef struct {
   /*INSTANCES*/
   cruiseCtr_setSpeed_ctx_type cruiseCtr_setSpeed_ctx_tab[1];
   cruiseCtr_controlSpeed_ctx_type cruiseCtr_controlSpeed_ctx_tab[1];
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_pre_2_ctx_type Lustre_pre_2_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Lustre_arrow_2_ctx_type Lustre_arrow_2_ctx_tab[1];
} cruiseCtr_cruiseCtr_ctx_type;

