/* This file was generated by lv6 version 6.101.27. */
/*  lv6 -cc switch.lus -n Switch */
/* on c74 the 08/02/2025 at 07:06:02 */

#include <stdlib.h>
#include <string.h>

#include "lustre_consts.h"

#ifndef _switch_Switch_H_FILE
#define _switch_Switch_H_FILE
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx();
void Lustre_arrow_step(_integer ,_integer ,_integer *,Lustre_arrow_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx();
void Lustre_pre_get(_integer *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_integer ,Lustre_pre_ctx_type*);

void switch_Switch_ctx_reset(switch_Switch_ctx_type* ctx);
switch_Switch_ctx_type* switch_Switch_ctx_new_ctx();
void switch_Switch_step(_boolean ,_integer *,_integer *,switch_Switch_ctx_type*);

/////////////////////////////////////////////////
#endif
